# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Test library"
  lane :test do
    sh "cd .. && swift test --enable-test-discovery --enable-code-coverage"
  end

  desc "Build sample"
  lane :build do
    xcodebuild(
    project: "Example/Example.xcodeproj",
    scheme: "Example",
    configuration: "Debug",
    build: true,
    destination: "platform=iOS Simulator,name=iPhone SE (3rd generation)"
  )
  end
end
